name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: first
        id: step1
        run: |
          TXT=$(ls -la)
          echo $TXT
          delimiter="$(openssl rand -hex 8)"
          echo "text<<${delimiter}" >> "${GITHUB_ENV}"
          echo $TXT >> "${GITHUB_ENV}"
          echo "${delimiter}" >> "${GITHUB_ENV}"
      - name: second
        id: step2
        run: |
          echo ${{ env.text }}
