name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: first
        id: step1
        run: |
          TXT=$(ls -la)
          TXT="${TXT//'%'/'%25'}"
          TXT="${TXT//$'\n'/'%0A'}"
          TXT="${TXT//$'\r'/'%0D'}"
          echo "text=$TXT" >> $GITHUB_ENV
      - name: second
        id: step2
        run: |
          echo ${{ env.text }}
